name: GitHub App token
author: Thibault Derousseaux <tibdex@gmail.com>
description: Run a GitHub Action as a GitHub App instead of using secrets.GITHUB_TOKEN or a personal access token.
inputs:
  app_id:
    description: ID of the GitHub App.
    required: true
  private_key:
    description: Private key of the GitHub App (can be Base64 encoded).
    required: true
  installation_id:
    description: The ID of the installation for which the token will be requested (defaults to the ID of the repository's installation).
  repository:
    description: The full name of the repository for which the token will be requested (defaults to the current repository).
  options:
    description: Additional options for generating the token (see https://github.com/octokit/auth-app.js#installation-authentication). Must be a string with a JSON object.
outputs:
  token:
    description: An installation token for the GitHub App on the requested repository.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: unlock
  color: gray-dark
