name: GitHub App token
author: Thibault Derousseaux <tibdex@gmail.com>
description: Run a GitHub Action as a GitHub App instead of using secrets.GITHUB_TOKEN or a personal access token.
inputs:
  app_id:
    description: ID of the GitHub App.
    required: true
  private_key:
    description: Private key of the GitHub App (can be Base64 encoded).
    required: true
  installation_id:
    description: The ID of the installation for which the token will be requested (defaults to the ID of the repository's installation).
  repository:
    description: The full name of the repository for which the token will be requested (defaults to the current repository).
  permissions:
    description: The JSON-stringified permissions granted to the token (defaults to all the GitHub app permissions, see https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app).
outputs:
  token:
    description: An installation token for the GitHub App on the requested repository.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: unlock
  color: gray-dark
